### PR TITLE
Adapt for result-returning Assemble.eval

### LINKED ISSUE #3: Better exit code error messages
We should try to extract better error messages when compiled programs terminate on error conditions. It should produce the same return string as the interpreter's errors.

### LINKED ISSUE #4: Differentiate segfault from other errors

### PR DESCRIPTION
**Pull request by max-heller**
Companion to brown-cs126/hw4#18

### CODE REVIEW

**Comment by dwoos** [comment]
Right now, all errors are treated the same--if, for instance, the interpreter raises `Not_found` and the compiler segfaults, as long as there's a `.err` file the test succeeds. Will that still be the case after this change?

**Comment by max-heller** [comment]
> Right now, all errors are treated the same--if, for instance, the interpreter raises `Not_found` and the compiler segfaults, as long as there's a `.err` file the test succeeds. Will that still be the case after this change?

Yes, this won't distinguish segfaults and the like from expected errors as of now. I have #4 open to track that aspect.

**Review by dwoos — COMMENTED** [review]
LGTM.

**Comment by max-heller** [comment]
It does now @dwoos. Can you take another look?

**Pull request merged**
